// <auto-generated />
using System;
using API_Fundamentals.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Fundamentals.Migrations
{
    [DbContext(typeof(StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Fundamentals.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "contact@techsolutions.com",
                            Name = "Tech Solutions Inc"
                        },
                        new
                        {
                            Id = 2,
                            Email = "info@globallogistics.net",
                            Name = "Global Logistics"
                        },
                        new
                        {
                            Id = 3,
                            Email = "hello@creativedesigns.io",
                            Name = "Creative Designs"
                        },
                        new
                        {
                            Id = 4,
                            Email = "support@healthfirst.org",
                            Name = "HealthFirst Group"
                        },
                        new
                        {
                            Id = 5,
                            Email = "sales@modernretail.com",
                            Name = "Modern Retailers"
                        });
                });

            modelBuilder.Entity("API_Fundamentals.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 3, 2, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4823),
                            TotalAmount = 492.219870277506m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 2, 18, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4834),
                            TotalAmount = 481.372226767036m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 3, 3, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4836),
                            TotalAmount = 123.952310683322m
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 3, 2, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4838),
                            TotalAmount = 235.652040401718m
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 2, 26, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4839),
                            TotalAmount = 264.111623079825m
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 2, 23, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4842),
                            TotalAmount = 298.039250810489m
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 2, 21, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4844),
                            TotalAmount = 60.1311937855346m
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 2, 21, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4845),
                            TotalAmount = 449.068948399257m
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 3, 3, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4847),
                            TotalAmount = 142.89739252972m
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 3, 6, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4849),
                            TotalAmount = 21.3036805196244m
                        },
                        new
                        {
                            Id = 11,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 2, 22, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4850),
                            TotalAmount = 329.185040417522m
                        },
                        new
                        {
                            Id = 12,
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 2, 23, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4851),
                            TotalAmount = 475.088011120991m
                        },
                        new
                        {
                            Id = 13,
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 2, 12, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4852),
                            TotalAmount = 33.5244002551214m
                        },
                        new
                        {
                            Id = 14,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 3, 12, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4853),
                            TotalAmount = 199.772996596152m
                        },
                        new
                        {
                            Id = 15,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 2, 23, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4855),
                            TotalAmount = 295.658671538789m
                        },
                        new
                        {
                            Id = 16,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 3, 8, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4856),
                            TotalAmount = 85.5950573997863m
                        },
                        new
                        {
                            Id = 17,
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 2, 13, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4857),
                            TotalAmount = 451.220211175506m
                        },
                        new
                        {
                            Id = 18,
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 2, 28, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4912),
                            TotalAmount = 201.29849647634m
                        },
                        new
                        {
                            Id = 19,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 3, 9, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4913),
                            TotalAmount = 371.946899715216m
                        },
                        new
                        {
                            Id = 20,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 3, 7, 10, 10, 33, 344, DateTimeKind.Utc).AddTicks(4915),
                            TotalAmount = 218.096809034224m
                        });
                });

            modelBuilder.Entity("API_Fundamentals.Core.Entities.Order", b =>
                {
                    b.HasOne("API_Fundamentals.Core.Entities.Customer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Fundamentals.Core.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
